"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _catalog_resource_grid from './catalog-resource-grid.bones.json'

configureBoneyard({"color":"#dbe6eb","animate":"shimmer","shimmerColor":"#edf4f6","speed":"1.8s","stagger":35,"transition":300})

registerBones({
  "catalog-resource-grid": _catalog_resource_grid,
})
