-- Ejecuta este archivo una vez desde Supabase Dashboard > SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on update cascade on delete cascade,
  name varchar(100) not null,
  role varchar(20) not null default 'user' check (role in ('admin', 'user')),
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name varchar(80) not null unique,
  slug varchar(80) not null unique,
  description varchar(240),
  created_at timestamptz not null default now()
);

create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  title varchar(140) not null,
  slug varchar(180) not null unique,
  description text not null,
  level varchar(30) not null check (level in ('Inicial', 'Intermedio', 'Avanzado')),
  duration_hours integer not null check (duration_hours > 0),
  image_url varchar(500) not null,
  featured boolean not null default false,
  category_id bigint not null references public.categories(id) on update cascade on delete restrict,
  author_id uuid not null references public.profiles(id) on update cascade on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_resources_category_id on public.resources(category_id);
create index if not exists idx_resources_author_id on public.resources(author_id);
create index if not exists idx_resources_created_at on public.resources(created_at desc);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)),
    case when new.raw_app_meta_data ->> 'role' = 'admin' then 'admin' else 'user' end
  )
  on conflict (id) do update
  set name = excluded.name,
      role = excluded.role;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of raw_user_meta_data, raw_app_meta_data on auth.users
for each row execute function public.handle_new_user();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists resources_set_updated_at on public.resources;
create trigger resources_set_updated_at
before update on public.resources
for each row execute function public.set_updated_at();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated, service_role;

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.resources enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles for select
to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists "profiles_public_author_read" on public.profiles;
create policy "profiles_public_author_read"
on public.profiles for select
to anon, authenticated
using (true);

drop policy if exists "categories_public_read" on public.categories;
create policy "categories_public_read"
on public.categories for select
to anon, authenticated
using (true);

drop policy if exists "categories_admin_insert" on public.categories;
create policy "categories_admin_insert"
on public.categories for insert
to authenticated
with check (public.is_admin());

drop policy if exists "categories_admin_update" on public.categories;
create policy "categories_admin_update"
on public.categories for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "categories_admin_delete" on public.categories;
create policy "categories_admin_delete"
on public.categories for delete
to authenticated
using (public.is_admin());

drop policy if exists "resources_public_read" on public.resources;
create policy "resources_public_read"
on public.resources for select
to anon, authenticated
using (true);

drop policy if exists "resources_admin_insert" on public.resources;
create policy "resources_admin_insert"
on public.resources for insert
to authenticated
with check (public.is_admin() and author_id = auth.uid());

drop policy if exists "resources_admin_update" on public.resources;
create policy "resources_admin_update"
on public.resources for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "resources_admin_delete" on public.resources;
create policy "resources_admin_delete"
on public.resources for delete
to authenticated
using (public.is_admin());

grant usage on schema public to anon, authenticated, service_role;
grant select on public.categories, public.resources to anon, authenticated, service_role;
revoke select on public.profiles from anon, authenticated;
grant select (id, name) on public.profiles to anon, authenticated;
grant select on public.profiles to service_role;
grant insert, update, delete on public.categories, public.resources to authenticated, service_role;
grant insert, update, delete on public.profiles to service_role;
grant usage, select on all sequences in schema public to authenticated, service_role;
